"""llm-gateway — a small, production-style API gateway in front of the Claude API.

A focused example of the fundamentals a backend/AI engineer is expected to ship:
  - Type hints + Pydantic validation
  - async endpoint + await on an external API call
  - Testable with pytest + mock (see tests/test_main.py)
  - FastAPI routing / request body / dependency injection / HTTPException
  - Request-logging middleware + lifespan
  - Calls the Claude API and returns the result

What it does: POST /v1/complete takes a prompt -> calls Claude -> returns the generated text.

Run (install deps first):
    uv add fastapi "uvicorn[standard]" anthropic
    uv add --dev pytest pytest-asyncio ruff mypy

    # Needs an API key (environment variable):
    export ANTHROPIC_API_KEY=sk-...            # official Claude
    # Or an Anthropic-compatible endpoint (just change base_url + key):
    # export ANTHROPIC_BASE_URL=https://...    # the SDK reads this automatically
    export GATEWAY_API_KEY=my-secret           # this gateway's own auth key

    uv run uvicorn main:app --reload

Try it:      http://127.0.0.1:8000/docs
Type check:  uv run mypy --strict main.py
"""

import os
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import cast

import anthropic
from anthropic import AsyncAnthropic
from fastapi import Depends, FastAPI, Header, HTTPException, Request
from pydantic import BaseModel, Field

# ============================================================
# Config (read from environment variables, never hard-coded)
# ============================================================

DEFAULT_MODEL = "claude-opus-4-8"                 # default model recommended by the official API reference
# This gateway's own auth key (note: this is NOT the same as Claude's ANTHROPIC_API_KEY)
GATEWAY_API_KEY = os.environ.get("GATEWAY_API_KEY", "dev-secret")


# ============================================================
# lifespan: build a *shared* Claude client at startup, reuse it for the whole process
# ============================================================

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Build the AsyncAnthropic client once at startup and attach it to app.state for reuse.

    Why build it in lifespan: creating the client has overhead; we should not
    rebuild it on every request. AsyncAnthropic() reads ANTHROPIC_API_KEY /
    ANTHROPIC_BASE_URL from the environment automatically.
    """
    print("[lifespan] startup: creating shared Claude client")
    app.state.llm = AsyncAnthropic()              # shared resource: see the get_llm dependency
    yield
    print("[lifespan] shutdown: cleaning up client")
    await app.state.llm.close()


app = FastAPI(title="llm-gateway", lifespan=lifespan)


# ============================================================
# middleware: request logging — print method/path/latency for every request
# ============================================================

@app.middleware("http")
async def log_requests(request: Request, call_next):  # type: ignore[no-untyped-def]
    start = time.perf_counter()
    response = await call_next(request)
    elapsed = time.perf_counter() - start
    print(f"[req] {request.method} {request.url.path} -> {response.status_code} ({elapsed:.3f}s)")
    return response


# ============================================================
# Dependencies: auth + fetch the shared client (FastAPI Depends)
# ============================================================

def verify_api_key(x_api_key: str = Header()) -> str:
    """Validate this gateway's access credential from the X-API-Key header. Wrong key -> 401."""
    if x_api_key != GATEWAY_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")
    return x_api_key


def get_llm(request: Request) -> AsyncAnthropic:
    """Return the shared client built in lifespan.

    Extracting this as a dependency has a nice benefit: tests can swap it out
    with app.dependency_overrides for a fake client, so they *never actually
    call Claude* (see the test file) — this is the mocking idea in practice.
    """
    # app.state is untyped (attribute access returns Any); use cast to tell mypy what it is.
    return cast(AsyncAnthropic, request.app.state.llm)


# ============================================================
# Pydantic models: request-body validation + response structure
# ============================================================

class CompleteRequest(BaseModel):
    prompt: str = Field(min_length=1, max_length=10000, description="the prompt to send to the model")
    max_tokens: int = Field(default=1024, gt=0, le=8192, description="max tokens to generate")
    model: str = Field(default=DEFAULT_MODEL, description="which model to use")


class CompleteResponse(BaseModel):
    text: str                    # the text generated by the model
    model: str                   # the model actually used
    input_tokens: int            # input token count (for billing)
    output_tokens: int           # output token count


# ============================================================
# Endpoint: POST /v1/complete — take a prompt, call Claude, return the result
# ============================================================

@app.post("/v1/complete", response_model=CompleteResponse)
async def complete(
    req: CompleteRequest,                              # request body validated automatically
    api_key: str = Depends(verify_api_key),            # auth first
    llm: AsyncAnthropic = Depends(get_llm),            # inject the shared client
) -> CompleteResponse:
    """async endpoint: while awaiting Claude, the server can handle other requests."""
    try:
        # Minimal call: model / max_tokens / messages is all you need (official API reference)
        message = await llm.messages.create(
            model=req.model,
            max_tokens=req.max_tokens,
            messages=[{"role": "user", "content": req.prompt}],
        )
    except anthropic.APIStatusError as e:              # Claude returned an error status code
        # Translate the upstream error into a gateway 502 (Bad Gateway): not our fault, it's upstream
        raise HTTPException(status_code=502, detail=f"LLM error: {e.message}") from e
    except anthropic.APIConnectionError as e:          # could not reach Claude
        raise HTTPException(status_code=503, detail="LLM unavailable") from e

    # The response content is a list of blocks; join their text (getattr keeps mypy happy)
    text = "".join(getattr(b, "text", "") for b in message.content)
    return CompleteResponse(
        text=text,
        model=message.model,
        input_tokens=message.usage.input_tokens,
        output_tokens=message.usage.output_tokens,
    )


@app.get("/healthz")
def healthz() -> dict[str, str]:
    """Health-check endpoint: used by CI / deployment to confirm the service is alive (no auth)."""
    return {"status": "ok"}
